name: Publish To GCR
on:
  push:
    branches: [ master ]
env:
  GCLOUD_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
  GCLOUD_REGION: ${{ secrets.GCLOUD_REGIONS }}
  PROJECT_ORGANIZATION: ${{ secrets.PROJECT_ORGANIZATION }}
  DOCKER_IMAGE: ${{ secrets.DOCKER_REGISTRY_URL }}
  GCLOUD_SA_KEY: ${{ secrets.GCLOUD_SA_KEY }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.m2/repository
          key: ${{ runner.os }}-gradle-test-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-test-
      - name: Setup GraalVM CE
        uses: DeLaGuardo/setup-graalvm@3.1
        with:
          graalvm-version: 21.1.0.java11
      - name: Install Native Image
        run: gu install native-image
      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${GCLOUD_SA_KEY}
          project_id: ${GCLOUD_PROJECT_ID}
          export_default_credentials: true
      - name: Docker Login
        run: |
          gcloud auth configure-docker
      - name: Build And Push Docker Image
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
        run: |
          ./gradlew dockerPushNative --no-daemon
      - name: Deploy Cloud Run
          run: |
            gcloud run deploy music-search --quiet \
              --image "${DOCKER_IMAGE}" --project "${PROJECT_ORGANIZATION}" \
              --region "${GCLOUD_REGION}" --platform managed --allow-unauthenticated --format json