name: Publish To GCR
on:
  push:
    tags:
      - 'v*'
env:
  GCLOUD_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
  GCLOUD_REGION: us-central1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-test-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-test-
      - name: Setup GraalVM CE
        uses: DeLaGuardo/setup-graalvm@3.1
        with:
          graalvm-version: 21.1.0.java11
      - name: Run Tests
        run: ./gradlew check --no-daemon
      - name: Install Native Image
        run: gu install native-image
      - name: Docker Login
        run: |
          gcloud auth configure-docker




      - name: Build And Push Docker Image
        env:
          DOCKER_IMAGE: ${{ secrets.DOCKER_REGISTRY_URL }}/${{ secrets.PROJECT_ORGANIZATION }}/${{ secrets.PROJECT_ID }}
          TESTCONTAINERS_RYUK_DISABLED: true
        run: |
          ./gradlew check dockerPushNative --no-daemon
      - name: Deploy Cloud Run
        run: |
          DOCKER_IMAGE_REPOSITORY=$(docker images --format "{{.Repository}}" | grep music-search)
          DOCKER_IMAGE=$(docker images --format "{{.Repository}}:{{.Tag}}" "${DOCKER_IMAGE_REPOSITORY}" )

          gcloud run deploy ${{ secrets.PROJECT_ID }} --quiet \
            --image "${DOCKER_IMAGE}" --project "${secrets.PROJECT_ORGANIZATION}" \
            --region "${GCLOUD_REGION}" --platform managed --allow-unauthenticated --format json
