name: Publish To GCR
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.m2/repository
          key: ${{ runner.os }}-gradle-test-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-test-
      - name: Setup GraalVM CE
        uses: DeLaGuardo/setup-graalvm@3.1
        with:
          graalvm-version: 21.1.0.java11
      - name: Install Native Image
        run: gu install native-image
      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
      - name: Docker Login
        run: |
          gcloud auth configure-docker
      - name: Build And Push Docker Image
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
        run: |
          export DOCKER_IMAGE="gcr.io/oci-micronaut/music-search"
          ./gradlew check dockerPushNative --no-daemon
      - name: Deploy Cloud Run
        run: |
          gcloud run deploy music-search --quiet \
            --image gcr.io/oci-micronaut/music-search --project oci-micronaut \
            --region us-central-1 --platform managed --allow-unauthenticated --format json
