micronaut:
  application:
    name: music-service
  server:
    cors:
      enabled: true
      configurations:
        allowedOrigins:
          - https://music-search.micronaut.io
  router:
    static-resources:
      default:
        enabled: true
        mapping: /**
        paths: classpath:ui
  codec:
    json:
      additionalTypes:
        - text/javascript
endpoints:
  info:
    enabled: true
    sensitive: false
