micronaut:
  application:
    name: music-service
  server:
    cors:
      enabled: true
  router:
    static-resources:
      default:
        enabled: true
        mapping: /**
        paths: classpath:public
  codec:
    json:
      additionalTypes:
        - text/javascript
endpoints:
  info:
    enabled: true
    sensitive: false
